development:
  adapter: postgresql
  database: weatherzapp_development
  host: localhost

test:
  adapter: postgresql
  database: weatherzapp_test
  host: localhost

production:
  adapter: postgresql
  database: weatherzapp_production
  host: localhost
