# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 656303b5b6d1ebd7979ca5c89e9a6e29579f6cb3626c39157c5ca4f5a44f2f5de87ee65405e5735f0acd5956fe521fa3e3eebe1c923aad04ca1ca2aadfede8aa

test:
  secret_key_base: 7f1e20832cb2aa6ca88648c33b9a359ba30ea7b1eba2603d56ffe5b4e3cf93203ce4bdb73b25b6f2cb398a66e53eea5e36d068d650babecc01c8bdf661b28058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
